class BookExtraRooms < ActiveRecord::Migration[5.0]
  def change
  	remove_reference :book_rooms, :room, index: true
  	add_column :book_rooms, :room2, :integer
  	add_column :book_rooms, :room3, :integer
  	add_column :book_rooms, :room4, :integer
	add_column :book_rooms, :room5, :integer
	add_column :book_rooms, :room6, :integer
	add_column :book_rooms, :room7, :integer
	add_column :book_rooms, :room8, :integer
	add_column :book_rooms, :room9, :integer
	add_column :book_rooms, :room10, :integer
	add_column :book_rooms, :room11, :integer
	add_column :book_rooms, :room12, :integer
  	add_column :book_rooms, :room13, :integer
  	add_column :book_rooms, :room14, :integer
	add_column :book_rooms, :room15, :integer
	add_column :book_rooms, :room16, :integer
	add_column :book_rooms, :room17, :integer
	add_column :book_rooms, :room18, :integer
	add_column :book_rooms, :room19, :integer
	add_column :book_rooms, :room20, :integer
	add_column :book_rooms, :room21, :integer
	add_column :book_rooms, :room22, :integer
  	add_column :book_rooms, :room23, :integer
  	add_column :book_rooms, :room24, :integer
	add_column :book_rooms, :room25, :integer
	add_column :book_rooms, :room26, :integer
	add_column :book_rooms, :room27, :integer
	add_column :book_rooms, :room28, :integer
	add_column :book_rooms, :room29, :integer
	add_column :book_rooms, :room30, :integer
	add_column :book_rooms, :room_no2, :string
  	add_column :book_rooms, :room_no3, :string
  	add_column :book_rooms, :room_no4, :string
	add_column :book_rooms, :room_no5, :string
	add_column :book_rooms, :room_no6, :string
	add_column :book_rooms, :room_no7, :string
	add_column :book_rooms, :room_no8, :string
	add_column :book_rooms, :room_no9, :string
	add_column :book_rooms, :room_no10, :string
	add_column :book_rooms, :room_no11, :string
	add_column :book_rooms, :room_no12, :string
  	add_column :book_rooms, :room_no13, :string
  	add_column :book_rooms, :room_no14, :string
	add_column :book_rooms, :room_no15, :string
	add_column :book_rooms, :room_no16, :string
	add_column :book_rooms, :room_no17, :string
	add_column :book_rooms, :room_no18, :string
	add_column :book_rooms, :room_no19, :string
	add_column :book_rooms, :room_no20, :string
	add_column :book_rooms, :room_no21, :string
	add_column :book_rooms, :room_no22, :string
  	add_column :book_rooms, :room_no23, :string
  	add_column :book_rooms, :room_no24, :string
	add_column :book_rooms, :room_no25, :string
	add_column :book_rooms, :room_no26, :string
	add_column :book_rooms, :room_no27, :string
	add_column :book_rooms, :room_no28, :string
	add_column :book_rooms, :room_no29, :string
	add_column :book_rooms, :room_no30, :string
	add_column :book_rooms, :room_price2, :integer
  	add_column :book_rooms, :room_price3, :integer
  	add_column :book_rooms, :room_price4, :integer
	add_column :book_rooms, :room_price5, :integer
	add_column :book_rooms, :room_price6, :integer
	add_column :book_rooms, :room_price7, :integer
	add_column :book_rooms, :room_price8, :integer
	add_column :book_rooms, :room_price9, :integer
	add_column :book_rooms, :room_price10, :integer
	add_column :book_rooms, :room_price11, :integer
	add_column :book_rooms, :room_price12, :integer
  	add_column :book_rooms, :room_price13, :integer
  	add_column :book_rooms, :room_price14, :integer
	add_column :book_rooms, :room_price15, :integer
	add_column :book_rooms, :room_price16, :integer
	add_column :book_rooms, :room_price17, :integer
	add_column :book_rooms, :room_price18, :integer
	add_column :book_rooms, :room_price19, :integer
	add_column :book_rooms, :room_price20, :integer
	add_column :book_rooms, :room_price21, :integer
	add_column :book_rooms, :room_price22, :integer
  	add_column :book_rooms, :room_price23, :integer
  	add_column :book_rooms, :room_price24, :integer
	add_column :book_rooms, :room_price25, :integer
	add_column :book_rooms, :room_price26, :integer
	add_column :book_rooms, :room_price27, :integer
	add_column :book_rooms, :room_price28, :integer
	add_column :book_rooms, :room_price29, :integer
	add_column :book_rooms, :room_price30, :integer
	add_column :book_rooms, :bill_price2, :integer
  	add_column :book_rooms, :bill_price3, :integer
  	add_column :book_rooms, :bill_price4, :integer
	add_column :book_rooms, :bill_price5, :integer
	add_column :book_rooms, :bill_price6, :integer
	add_column :book_rooms, :bill_price7, :integer
	add_column :book_rooms, :bill_price8, :integer
	add_column :book_rooms, :bill_price9, :integer
	add_column :book_rooms, :bill_price10, :integer
	add_column :book_rooms, :bill_price11, :integer
	add_column :book_rooms, :bill_price12, :integer
  	add_column :book_rooms, :bill_price13, :integer
  	add_column :book_rooms, :bill_price14, :integer
	add_column :book_rooms, :bill_price15, :integer
	add_column :book_rooms, :bill_price16, :integer
	add_column :book_rooms, :bill_price17, :integer
	add_column :book_rooms, :bill_price18, :integer
	add_column :book_rooms, :bill_price19, :integer
	add_column :book_rooms, :bill_price20, :integer
	add_column :book_rooms, :bill_price21, :integer
	add_column :book_rooms, :bill_price22, :integer
  	add_column :book_rooms, :bill_price23, :integer
  	add_column :book_rooms, :bill_price24, :integer
	add_column :book_rooms, :bill_price25, :integer
	add_column :book_rooms, :bill_price26, :integer
	add_column :book_rooms, :bill_price27, :integer
	add_column :book_rooms, :bill_price28, :integer
	add_column :book_rooms, :bill_price29, :integer
	add_column :book_rooms, :bill_price30, :integer
	add_column :book_rooms, :total, :integer
	add_column :bills, :room_number, :string
	add_column :bills, :room, :integer
  end
end
